# N Sharma 11/9/20
# loads the packages required for analysis
# add to as required
# Notes: 
#library(scico) # this is a pallette. This scico_palette_show() shows them all
## Skipping install of 'ggmosaic' from a github remote, the SHA1 (9dd8eb6e) has not changed since last install.
##   Use `force = TRUE` to force installation
if (!require("pacman")) install.packages("pacman")
pacman::p_load(ExperimentHub, 
               curatedMetagenomicData, 
               phyloseq,
               microbiome,
               forcats,
               stargazer,
               ggpubr,
               tidyverse,
               cowplot,
               vegan,
               broom,
               tsnemicrobiota,
               latex2exp,
               wesanderson,
               rmdrive,
               googledrive,
               knitr,
               ggtext,
               mdthemes,
               SIAMCAT,
               kableExtra,
               countrycode,
               treemapify,
               ggthemes,
               wesanderson,
               RColorBrewer,
               viridis,
               scico,
               ggmosaic,
               patchwork,
               Hmisc,
               officer,
               flextable,
               purrr,
               doBy,
               berryFunctions,
               table1,
               arsenal,
               progress,
               pROC,
               Polychrome,
               plyr,
               DiagrammeR,
               SpiecEasi,
               metagMisc,
               citr,
               knitr,
               MGnifyR,
               magick
               )
